export default {
	favoritesButton: document.querySelector('[data-add-favorites]'),
	cityInput: document.querySelector('[data-input-city]'),
	favoritiesList: document.querySelector('[data-favorities-list]'),
	swiperNavButtons: document.querySelectorAll('.header-wrapper-nav-button'),
	searchButton: document.querySelector('[data-search-button]'),
	curentTemp: document.querySelector('.days-current-temp'),
	currentLocation: document.querySelector('.days-city-title'),
	currentLocationFive: document.querySelector('.five-days-city-title'),
	daysWrapper: document.querySelector('.days-wrapper'),
	maxTempText: document.querySelector('[data-max-temp]'),
	minTempText: document.querySelector('[data-min-temp]'),
	currentDate: document.querySelector('.date-day'),
	currentDay: document.querySelector('.day-week'),
	currentMonth: document.querySelector('.date-month'),
	currentTime: document.querySelector('.date-time'),
	sunRise: document.querySelector('.sunrise'),
	sunSet: document.querySelector('.sunset'),
	sunBlock: document.querySelector('.sun-rise-set'),
	switchFiveDays: document.querySelector('[data-switch-five-days]'),
	switchOneDay: document.querySelector('[data-switch-one-day]'),
	homeSection: document.querySelector('.home'),
	citeBlock: document.querySelector('[data-cite-block]'),
	dateBlock: document.querySelector('.date-wrapper'),
	fiveDayContainer: document.querySelector('.five-day-container'),
	fiveDaysCityWeekday: document.querySelectorAll(
		'.five-days-city-list-weekday'
	),
};
